# Generated by Django 5.1.4 on 2025-01-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userID',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
