# Generated by Django 5.1.4 on 2025-01-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('customer', 'Customer'), ('affiliate', 'Affiliate')], default='customer', max_length=10),
        ),
    ]
