# Generated by Django 5.1.4 on 2025-01-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
