# Generated by Django 5.1.4 on 2025-01-13 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airbnb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='amenities',
            field=models.ManyToManyField(to='airbnb.amenity'),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='airbnb.houselisting'),
        ),
        migrations.AddField(
            model_name='availabledate',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='airbnb.houselisting'),
        ),
        migrations.AddField(
            model_name='photo',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='airbnb.houselisting'),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airbnb.propertytype'),
        ),
        migrations.AddField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='airbnb.houselisting'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airbnb.roomtype'),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='airbnb.houselisting'),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.houselisting'),
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'listing')},
        ),
    ]
