# Generated by Django 5.1.4 on 2025-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airbnb", "0007_houselisting_is_for_rent_houselisting_is_for_sale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="houselisting",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="houselisting",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
